name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurez Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 4 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/extracte_import_odoo:latest

      # Étape 5 : Déploiement sur le serveur Docker via SSH
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}  # Adresse IP ou domaine du serveur
          username: ${{ secrets.REMOTE_SERVER_USER }}  # Nom d'utilisateur SSH
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}  # Clé SSH privée
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/extracte_import_odoo:latest
            docker stop extracte_import_odoo || true
            docker rm extracte_import_odoo || true
            docker run -d --name extracte_import_odoo -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/extracte_import_odoo:latest
