name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Déclencher sur les pushs vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t extracte_import_odoo:latest .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag extracte_import_odoo:latest christiandibi/extracte_import_odoo:latest
          docker push christiandibi/extracte_import_odoo:latest

      - name: Deploy Container
        run: |
          docker stop extracte_import_odoo || true
          docker rm extracte_import_odoo || true
          docker run -d -p 5000:5000 --name extracte_import_odoo christiandibi/extracte_import_odoo:latest
